from BaseClasses import Item, ItemClassification

class PlateUpItem(Item):
    game = "plateup"
    
    def __init__(self, name, classification, code, player):
        super().__init__(name, classification, code, player)
        self.code = code

    def __repr__(self):
        return "<PlateUpItem {} (ID: {})>".format(self.name, self.code)


ITEMS = {
    #region Appliances
    "Hob": (1001, ItemClassification.useful),
    "Safe Hob": (10012, ItemClassification.useful),
    "Danger Hob": (10013, ItemClassification.progression),
    "Starting Hob": (10014, ItemClassification.filler),
    "Oven": (10015, ItemClassification.progression),
    "Microwave": (10016, ItemClassification.useful),
    "Gas Limiter": (10017, ItemClassification.useful),
    "Gas Override": (10018, ItemClassification.useful),
    "Sink": (1002, ItemClassification.useful),
    "Power Sink": (10022, ItemClassification.useful),
    "Soaking Sink": (10023, ItemClassification.useful),
    "Starting Sink": (10024, ItemClassification.filler),
    "Dishwasher": (10025, ItemClassification.progression),
    "Wash Basin": (10026, ItemClassification.progression),
    "Counter": (1003, ItemClassification.useful),
    "Workstation": (10032, ItemClassification.useful),
    "Freezer": (10033, ItemClassification.useful),
    "Prep Station": (10034, ItemClassification.useful),
    "Frozen Prep Station": (10035, ItemClassification.useful),
    "Dining Table": (1004, ItemClassification.useful),
    "Bar Table": (10042, ItemClassification.useful),
    "Basic Cloth Table": (10043, ItemClassification.useful),
    "Cheap Metal Table": (10044, ItemClassification.filler),
    "Fancy Cloth Table": (10045, ItemClassification.useful),
    "Coffee Table": (10046, ItemClassification.useful),
    "Starter Bin": (1005, ItemClassification.filler),
    "Bin": (10052, ItemClassification.filler),
    "Compactor Bin": (10053, ItemClassification.useful),
    "Composter Bin": (10054, ItemClassification.useful),
    "Expanded Bin": (10055, ItemClassification.useful),
    "Kitchen Floor Protector": (10056, ItemClassification.filler),
    "Rolling Pin": (1006, ItemClassification.useful),
    "Sharp Knife": (10062, ItemClassification.useful),
    "Scrubbing Brush": (10063, ItemClassification.useful),
    "Breadsticks": (1007, ItemClassification.filler),
    "Candle Box": (10072, ItemClassification.filler),
    "Napkins": (10073, ItemClassification.filler),
    "Sharp Cutlery": (10074, ItemClassification.useful),
    "Specials Menu": (10075, ItemClassification.filler),
    "Leftover Bags": (10076, ItemClassification.useful),
    "Supplies": (10077, ItemClassification.useful),
    "Hosting Stand": (10078, ItemClassification.filler),
    "Flower Pot": (10079, ItemClassification.useful),
    "Mop": (1008, ItemClassification.filler),
    "Lasting Mop": (10082, ItemClassification.useful),
    "Fast Mop": (10083, ItemClassification.useful),
    "Robot Mop": (10084, ItemClassification.useful),
    "Floor Buffer": (10085, ItemClassification.useful),
    "Robot Buffer": (10086, ItemClassification.useful),
    "Dish Rack": (10087, ItemClassification.useful),
    "Conveyor": (1009, ItemClassification.useful),
    "Grabber": (10092, ItemClassification.progression),
    "Smart Grabber": (10093, ItemClassification.progression),
    "Grabber Rotating": (10094, ItemClassification.progression),
    "Combiner": (10095, ItemClassification.useful),
    "Portioner": (10096, ItemClassification.useful),
    "Mixer": (10097, ItemClassification.useful),
    "Conveyor Mixer": (10098, ItemClassification.useful),
    "Heated Mixer": (10099, ItemClassification.useful),
    "Rapid Mixer": (100992, ItemClassification.useful),
    "Blueprint Cabinet": (1011, ItemClassification.filler),
    "Research Desk": (10112, ItemClassification.progression),
    "Blueprint Desk": (10113, ItemClassification.useful),
    "Discount Desk": (10114, ItemClassification.filler),
    "Clipboard Stand": (10115, ItemClassification.filler),
    "Copying Desk": (10116, ItemClassification.useful),
    "Trainers": (1012, ItemClassification.useful),
    "Wellies": (10122, ItemClassification.filler),
    "Work Boots": (10123, ItemClassification.filler),
    "Booking Desk": (1013, ItemClassification.filler),
    "Display Stand": (10132, ItemClassification.filler),
    "Dumbwaiter": (10133, ItemClassification.filler),
    "Teleporter": (10134, ItemClassification.useful),
    "Fire Extinguisher": (10135, ItemClassification.filler),
    "Ordering Terminal": (10136, ItemClassification.filler),
    "Specials Terminal": (10137, ItemClassification.filler),
    "Starter Plates": (1014, ItemClassification.filler),
    "Plates": (10142, ItemClassification.useful),
    "Auto Plater": (10143, ItemClassification.useful),
    # "Pot Stack": (10144, ItemClassification.filler),
    # "Serving Boards": (10145, ItemClassification.filler),
    # "Coffee Machine": (1015, ItemClassification.filler),
    # "Ice Dispenser": (10152, ItemClassification.filler),
    # "Milk Steamer": (10153, ItemClassification.filler),
    # "Woks": (10154, ItemClassification.filler),
    # "Lasagne Tray": (10155, ItemClassification.filler),
    # "Taco Trays": (10156, ItemClassification.filler),
    # "Mixing Bowl": (10157, ItemClassification.filler),
    # "Cake Tin": (10158, ItemClassification.filler),
    # "Brownie Tray": (10159, ItemClassification.filler),
    # "Cookie Tray": (1016, ItemClassification.filler),
    # "Cupcake Tray": (10162, ItemClassification.filler),
    # "Doughnut Tray": (10163, ItemClassification.filler),
    "Extra Life": (10164, ItemClassification.progression),
    #endregion
    #region Speed
    "Speed Upgrade Player": (10, ItemClassification.progression),
    "Speed Upgrade Appliance": (11, ItemClassification.progression),
    "Speed Upgrade Cook": (12, ItemClassification.progression),
    "Speed Upgrade Chop": (13, ItemClassification.progression),
    "Speed Upgrade Clean": (14, ItemClassification.progression),
    #endregion
    #region traps
    "EVERYTHING IS ON FIRE": (20000, ItemClassification.trap),
    "Super Slow": (20001, ItemClassification.trap),
    "Random Customer Card": (20002, ItemClassification.trap),
    #endregion
}

FILLER_ITEMS = {
    "Spork": (200011, ItemClassification.filler),
    "Broken Plate": (200021, ItemClassification.filler),
    "Dented Pot": (20003, ItemClassification.filler),
    "Burnt Toast": (20004, ItemClassification.filler),
    "Melted Ladle": (20005, ItemClassification.filler),
    "Sticky Tray": (20006, ItemClassification.filler),
    "Bent Fork": (20007, ItemClassification.filler),
    "Chipped Cup": (20008, ItemClassification.filler),
    "Greasy Napkin": (20009, ItemClassification.filler),
    "Cracked Bowl": (20010, ItemClassification.filler),
    "Overcooked Steak": (20011, ItemClassification.filler),
    "Undercooked Pasta": (20012, ItemClassification.filler),
    "Mismatched Silverware": (20013, ItemClassification.filler),
    "Soggy Bread": (20014, ItemClassification.filler),
    "Expired Milk": (20015, ItemClassification.filler),
    "Rusty Can Opener": (20016, ItemClassification.filler),
    "Bent Whisk": (20017, ItemClassification.filler),
    "Burnt Pizza Slice": (20018, ItemClassification.filler),
    "Chipped Teacup": (20019, ItemClassification.filler),
    "Wilted Lettuce": (20020, ItemClassification.filler),
    "Cold Soup": (20021, ItemClassification.filler),
    "Stale Donut": (20022, ItemClassification.filler),
    "Sticky Syrup Bottle": (20023, ItemClassification.filler),
    "Broken Cheese Grater": (20024, ItemClassification.filler),
    "Melted Ice Cream": (20025, ItemClassification.filler),
    "Overfilled Trash Bag": (20026, ItemClassification.filler),
    "Cracked Salt Shaker": (20027, ItemClassification.filler),
    "Dented Baking Pan": (20028, ItemClassification.filler),
    "Old Coffee Grounds": (20029, ItemClassification.filler),
    "Burnt Waffle": (20030, ItemClassification.filler),
    "Smashed Tomato": (20031, ItemClassification.filler),
    "Torn Apron": (20032, ItemClassification.filler),
    "Overflowing Sink": (20033, ItemClassification.filler),
    "Frayed Dish Towel": (20034, ItemClassification.filler),
    "Cracked Pepper Grinder": (20035, ItemClassification.filler),
    "Leaky Oil Bottle": (20036, ItemClassification.filler),
    "Overboiled Rice": (20037, ItemClassification.filler),
    "Cold French Fries": (20038, ItemClassification.filler),
    "Chipped Wine Glass": (20039, ItemClassification.filler),
    "Broken Corkscrew": (20040, ItemClassification.filler),
    "Squashed Burger Bun": (20041, ItemClassification.filler),
    "Overfilled Ice Bucket": (20042, ItemClassification.filler),
    "Soggy Cereal": (20043, ItemClassification.filler),
    "Flattened Soda Can": (20044, ItemClassification.filler),
    "Forgotten Takeout": (20045, ItemClassification.filler),
    "Wilted Herb Bunch": (20046, ItemClassification.filler),
    "Leaking Soup Ladle": (20047, ItemClassification.filler),
    "Torn Recipe Page": (20048, ItemClassification.filler),
    "Overused Cutting Board": (20049, ItemClassification.filler),
    "Squashed Lemon": (20050, ItemClassification.filler),
    "Warped Wooden Spoon": (20051, ItemClassification.filler),
    "Overturned Mixing Bowl": (20052, ItemClassification.filler),
    "Dropped Ice Cube": (20053, ItemClassification.filler),
    "Grease-Stained Menu": (20054, ItemClassification.filler),
    "Burned Biscuit": (20055, ItemClassification.filler),
    "Unopened Ketchup Packet": (20056, ItemClassification.filler),
    "Empty Sugar Jar": (20057, ItemClassification.filler),
    "Cracked Pie Dish": (20058, ItemClassification.filler),
    "Tangled Spaghetti": (20059, ItemClassification.filler),
    "Soggy Pancake": (20060, ItemClassification.filler),
    "Wilted Basil Leaves": (20061, ItemClassification.filler),
    "Splattered Eggshells": (20062, ItemClassification.filler),
    "Chipped Measuring Cup": (20063, ItemClassification.filler),
    "Tipped Over Milk Carton": (20064, ItemClassification.filler),
    "Forgotten Shopping List": (20065, ItemClassification.filler),
    "Sticky Honey Jar": (20066, ItemClassification.filler),
    "Melted Cheese Slice": (20067, ItemClassification.filler),
    "Crushed Cereal Box": (20068, ItemClassification.filler),
    "Overcooked Fish Fillet": (20069, ItemClassification.filler),
    "Lukewarm Tea Bag": (20070, ItemClassification.filler),
    "Stale Bread Loaf": (20071, ItemClassification.filler),
    "Half-Eaten Doughnut": (20072, ItemClassification.filler),
    "Smashed Strawberry": (20073, ItemClassification.filler),
    "Old Oven Mitt": (20074, ItemClassification.filler),
    "Leaky Syrup Bottle": (20075, ItemClassification.filler),
    "Burned Bacon Strip": (20076, ItemClassification.filler),
    "Unraveled Whipped Cream Can": (20077, ItemClassification.filler),
    "Torn Paper Napkin": (20078, ItemClassification.filler),
    "Greasy Pizza Box": (20079, ItemClassification.filler),
    "Crumpled Takeout Bag": (20080, ItemClassification.filler),
    "Cracked Egg": (20081, ItemClassification.filler),
    "Overfilled Coffee Cup": (20082, ItemClassification.filler),
    "Flattened Croissant": (20083, ItemClassification.filler),
    "Dirty Apron": (20084, ItemClassification.filler),
    "Squished Cupcake": (20085, ItemClassification.filler),
    "Faded Recipe Card": (20086, ItemClassification.filler),
    "Cracked Ice Tray": (20087, ItemClassification.filler),
    "Sticky Soda Lid": (20088, ItemClassification.filler),
    "Overused Rolling Pin": (20089, ItemClassification.filler),
    "Unopened Mustard Packet": (20090, ItemClassification.filler),
    "Dented Saucepan": (20091, ItemClassification.filler),
    "Leaky Teapot": (20092, ItemClassification.filler),
    "Flattened Burger Patty": (20093, ItemClassification.filler),
    "Warped Baking Sheet": (20094, ItemClassification.filler),
    "Mushy Banana": (20095, ItemClassification.filler),
    "Crushed Ice Cream Cone": (20096, ItemClassification.filler),
    "Cold Grilled Cheese": (20097, ItemClassification.filler),
    "Wilted Spinach Leaves": (20098, ItemClassification.filler),
    "Forgotten Leftovers": (20099, ItemClassification.filler),
    "Torn Oven Glove": (20100, ItemClassification.filler),
    "Dented Measuring Spoon": (20101, ItemClassification.filler),
    "Unraveled Aluminum Foil": (20102, ItemClassification.filler),
    "Clogged Pepper Shaker": (20103, ItemClassification.filler),
    "Overboiled Potatoes": (20104, ItemClassification.filler),
    "Sticky BBQ Sauce Bottle": (20105, ItemClassification.filler),
    "Overseasoned Soup": (20106, ItemClassification.filler),
    "Cracked Serving Tray": (20107, ItemClassification.filler),
    "Soaked Paper Straw": (20108, ItemClassification.filler),
    "Chipped Salad Bowl": (20109, ItemClassification.filler),
    "Soggy French Toast": (20110, ItemClassification.filler),
    "Flattened Dinner Roll": (20111, ItemClassification.filler),
    "Faded Restaurant Sign": (20112, ItemClassification.filler),
    "Cracked Ice Bucket": (20113, ItemClassification.filler),
    "Torn Placemat": (20114, ItemClassification.filler),
    "Burned Muffin": (20115, ItemClassification.filler),
    "Dropped Cooking Spoon": (20116, ItemClassification.filler),
    "Chipped Pasta Bowl": (20117, ItemClassification.filler),
    "Sticky Cookie Sheet": (20118, ItemClassification.filler),
    "Overripe Tomato": (20119, ItemClassification.filler),
    "Unwashed Cutting Board": (20120, ItemClassification.filler),
    "Dropped Popcorn Bag": (20121, ItemClassification.filler),
    "Soggy Taco Shell": (20122, ItemClassification.filler),
    "Broken Soda Dispenser": (20123, ItemClassification.filler),
    "Leaking Olive Oil Bottle": (20124, ItemClassification.filler),
    "Smashed Avocado": (20125, ItemClassification.filler),
    "Burnt Pancake": (20126, ItemClassification.filler),
    "Dented Tupperware Lid": (20127, ItemClassification.filler),
    "Torn Dish Cloth": (20128, ItemClassification.filler),
    "Overfilled Soup Bowl": (20129, ItemClassification.filler),
    "Greasy Fryer Basket": (20130, ItemClassification.filler),
    "Dried Out Cheese Block": (20131, ItemClassification.filler),
    "Cracked Milkshake Glass": (20132, ItemClassification.filler),
    "Leaking Coffee Pot": (20133, ItemClassification.filler),
    "Chipped Butter Dish": (20134, ItemClassification.filler),
    "Mushy Blueberries": (20135, ItemClassification.filler),
    "Torn Cheesecloth": (20136, ItemClassification.filler),
    "Overused Ice Cream Scoop": (20137, ItemClassification.filler),
    "Flattened Whipped Cream Tub": (20138, ItemClassification.filler),
    "Wilted Rosemary Sprig": (20139, ItemClassification.filler),
    "Burned Apple Pie": (20140, ItemClassification.filler),
}


